export let books = [
  {
    id: 1,
    title: "OnePiece n°1",
    editor: 1,
    category: 1,
    nmbPage: 150,
    resume: "JSp...JSP...JSP",
    author: 1,
    year: "1997",
    image: "http://localhost:3000/images/OnePiece1.jpg",

    extrait: "http://localhost:3000/api/mangas",
    created: new Date(),
  },
  {
    id: 2,
    title: "Naruto n°1",
    category: 1,
    nmbPage: 150,
    resume: "JSP...JSP...JSP",
    author: 2,
    editor: 1,
    year: "2002",
    image: "http://localhost:3000/images/Naruto1.jpg",
    extrait: "http://localhost:3000/api/mangas",
    created: new Date(),
  },
  {
    id: 3,
    title: "Bleach n°1",
    category: 1,
    nmbPage: 150,
    resume: "JSP...JSP...JSP",
    author: 3,
    editor: 2,
    year: "2004",
    image: "http://localhost:3000/images/Bleach1.jfif",
    extrait: "http://localhost:3000/api/mangas",
    created: new Date(),
  },
  {
    id: 4,
    title: "Jujutsu Kaisen n°1",
    category: 1,
    nmbPage: 150,
    resume: "JSP...JSP...JSP",
    author: 4,
    editor: 3,
    year: "2020",
    image: "http://localhost:3000/images/Jujutsu-Kaisen1.jpg",
    extrait: "http://localhost:3000/api/mangas",
    created: new Date(),
  },
  {
    id: 5,
    title: "Berserk n°1",
    category: 1,
    nmbPage: 150,
    resume: "JSP...JSP...JSP",
    author: 5,
    editor: 2,
    year: "2017",

    image: "http://localhost:3000/images/Berserk1.jpg",
    extrait: "http://localhost:3000/api/mangas",
    created: new Date(),
  },
];
